# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: "irrenasem/weatherapp:latest"
          command: ["python"]
          args: ["weather_app.py", "{{ .Values.weather-app.city_name }}", "{{ .Values.weather-app.future_date }}"]
          env:
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.weather-app.apiToken }}"
                key: apiToken

